-- 코드를 입력하세요
SELECT
    USER.USER_ID,
    USER.NICKNAME,
    BOARD.TOTAL_SALES

FROM
USED_GOODS_USER USER
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
) BOARD
    ON USER.USER_ID = BOARD.WRITER_ID

ORDER BY
    BOARD.TOTAL_SALES ASC
