-- 코드를 입력하세요
SELECT
    MONTH(A.START_DATE) AS MONTH,
    B.CAR_ID,
    COUNT(*) AS RECORDS
    

FROM
CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN (
SELECT CAR_ID, COUNT(*) AS SUM_RENT

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    
GROUP BY CAR_ID

HAVING COUNT(*) >= 5
) B
    ON A.CAR_ID = B.CAR_ID

WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'

GROUP BY
    MONTH(A.START_DATE),
    A.CAR_ID
    
ORDER BY
    MONTH,
    CAR_ID DESC
    
    