
SELECT
    A.SCORE,
    C.EMP_NO,
    C.EMP_NAME,
    C.POSITION,
    C.EMAIL

FROM
HR_DEPARTMENT E
JOIN (
HR_EMPLOYEES C
JOIN ((
SELECT EMP_NO, SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO) A
JOIN (
SELECT SUM(SCORE) AS SCORE
FROM HR_GRADE
GROUP BY EMP_NO
ORDER BY
    SCORE DESC
    LIMIT 1) B
    ON A.SCORE = B.SCORE)
    ON C.EMP_NO = A.EMP_NO)
    ON E.DEPT_ID = C.DEPT_ID    