-- 코드를 입력하세요
SELECT
    ICECREAM_INFO.INGREDIENT_TYPE,
    SUM(FIRST_HALF.TOTAL_ORDER) AS TOTAL_ORDER

FROM FIRST_HALF JOIN ICECREAM_INFO
    USING (FLAVOR)

GROUP BY
    ICECREAM_INFO.INGREDIENT_TYPE

ORDER BY
    TOTAL_ORDER 