-- 코드를 입력하세요
SELECT
    B.CATEGORY,
    B.MAX_PRICE,
    A.PRODUCT_NAME

FROM
    FOOD_PRODUCT A
    JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    ) B
        ON A.CATEGORY = B.CATEGORY AND
        A.PRICE = B.MAX_PRICE

WHERE
    A.CATEGORY = '과자' OR
    A.CATEGORY = '국' OR
    A.CATEGORY = '김치' OR
    A.CATEGORY = '식용유'

ORDER BY
    B.MAX_PRICE DESC
